name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build site
        env:
          IS_STATIC: true
          GITHUB_TOKEN: ${{ secrets.GENERATE_GITHUB_TOKEN || secrets.GITHUB_TOKEN }}
        run: yarn build

      - name: Add README to output
        run: |
          echo "This is the compiled static site for https://lissy93.github.io" > build/README.txt

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./build
      #     publish_branch: gh-pages

      - name: Deploy to gh-pages branch
        run: |
          git config --global user.name "liss-bot"
          git config --global user.email "alicia-gh-bot@mail.as93.net"
          git fetch origin gh-pages || true
          git switch --orphan temp-deploy
          git reset
          cp -r build/* .
          touch .nojekyll
          git add .
          git commit -m "Deploy static site"
          git push --force origin temp-deploy:gh-pages
    
